<template>
  <div class="Footer">
    <el-card>
    </el-card>
  </div>
</template>

<script>
export default {
  name: 'Footer',
  data () {
    return {
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang = 'scss'>
.Footer {
    .el-card{
        background-color: rgba(244,167,185,0.2);
        color: #333;
        text-align: center;
        line-height: 20px;
    }
}
</style>
